create table erp_employees (
    employee_id number generated by default as identity primary key,
    employee_name varchar2(100) not null,
    department varchar2(50) not null,
    salary number(10,2) not null,
    created_at date default sysdate
);

create table erp_customers (
    customer_id number generated by default as identity primary key,
    customer_name varchar2(100) not null,
    phone varchar2(20),
    city varchar2(50),
    created_at date default sysdate
);

create table erp_products (
    product_id number generated by default as identity primary key,
    product_name varchar2(100) not null,
    category varchar2(50),
    unit_price number(10,2) not null,
    stock_qty number not null,
    created_at date default sysdate
);

create table erp_orders (
    order_id number generated by default as identity primary key,
    customer_id number not null,
    order_date date default sysdate,
    total_amount number(12,2) default 0,
    status varchar2(20) default 'CREATED',
    constraint fk_erp_orders_customer
        foreign key (customer_id) references erp_customers(customer_id)
);

create table erp_order_items (
    order_item_id number generated by default as identity primary key,
    order_id number not null,
    product_id number not null,
    quantity number not null,
    unit_price number(10,2) not null,
    line_total number(12,2) not null,
    constraint fk_erp_order_items_order
        foreign key (order_id) references erp_orders(order_id),
    constraint fk_erp_order_items_product
        foreign key (product_id) references erp_products(product_id)
);
